
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int NE = 22;
  public static final int LT = 18;
  public static final int PLUS = 13;
  public static final int RBRACE = 27;
  public static final int RPAREN = 25;
  public static final int DECIMAL = 31;
  public static final int SEMI = 23;
  public static final int SHOW = 8;
  public static final int ON = 10;
  public static final int IDENTIFIER = 28;
  public static final int PATIENT = 2;
  public static final int IF = 11;
  public static final int LBRACE = 26;
  public static final int LPAREN = 24;
  public static final int GT = 17;
  public static final int LE = 20;
  public static final int DISCHARGE = 4;
  public static final int STRING = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int TEMPERATURE = 5;
  public static final int AGE = 9;
  public static final int GE = 19;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int ASSIGN = 12;
  public static final int INTEGER = 30;
  public static final int ADMIT = 3;
  public static final int APPOINTMENT = 7;
  public static final int WEIGHT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PATIENT",
  "ADMIT",
  "DISCHARGE",
  "TEMPERATURE",
  "WEIGHT",
  "APPOINTMENT",
  "SHOW",
  "AGE",
  "ON",
  "IF",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "GT",
  "LT",
  "GE",
  "LE",
  "EQ",
  "NE",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "IDENTIFIER",
  "STRING",
  "INTEGER",
  "DECIMAL"
  };
}

